###
POST http://localhost:8081/createPlace HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMyMGE5MGViNGRmODQzODk0OWI1OTY0IiwiZW1haWwiOiJsYW1vdWNoZUBnbWFpbC5jb20iLCJpYXQiOjE2NjMwODY1MzEsImV4cCI6MTY2MzExMTczMX0.zYzAFETpaTj_vvMbAvKD17id0ve442PFASfOZBcw3HA

{
    "name": "COWORK BASTILLE",
    "city": "Paris",
    "cp": 75004,
    "horaire":{
        "lundi":"9h-20h",
        "mardi": "9h-20h",
        "mercredi": "9h-20h",
        "jeudi": "9h-20h",
        "vendredi": "9h-20h",
        "samedi": "9h-20h",
        "dimanche": "11h-20h"
    }
}


###
GET http://localhost:8081/getPlace HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMyMGE5MGViNGRmODQzODk0OWI1OTY0IiwiZW1haWwiOiJsYW1vdWNoZUBnbWFpbC5jb20iLCJpYXQiOjE2NjMwODY1MzEsImV4cCI6MTY2MzExMTczMX0.zYzAFETpaTj_vvMbAvKD17id0ve442PFASfOZBcw3HA

###
POST http://localhost:8081/getPlaceById HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJlNzljNjI0ZDQ3MTAyYmIwY2MxNjYwIiwiZW1haWwiOiJzdW53dWtvbmdAZ21haWwuY29tIiwiaWF0IjoxNjU5NDU0ODI1LCJleHAiOjE2NTk0ODAwMjV9.T6ty88FqVNHMRgiZTBSjJu0vGxMgJ3lVfUq7TGFzZaY

{
    "id": "62e95018684d1822849593e9"
}

###
PATCH http://localhost:8081/updatePlace HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJlNzljNjI0ZDQ3MTAyYmIwY2MxNjYwIiwiZW1haWwiOiJzdW53dWtvbmdAZ21haWwuY29tIiwiaWF0IjoxNjU5NDU0ODI1LCJleHAiOjE2NTk0ODAwMjV9.T6ty88FqVNHMRgiZTBSjJu0vGxMgJ3lVfUq7TGFzZaY

{
    "id": "62e95018684d1822849593e9",
    "name": "COWORK BASTILLE",
    "city": "Paris",
    "cp": 75004,
    "horaire":{
        "lundi":"8h-19h",
        "mardi": "9h-21h",
        "mercredi": "9h-20h",
        "jeudi": "9h-20h",
        "vendredi": "9h-20h",
        "samedi": "9h-20h",
        "dimanche": "13h-20h"
    }
}

###
DELETE http://localhost:8081/deletePlace HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJlNzljNjI0ZDQ3MTAyYmIwY2MxNjYwIiwiZW1haWwiOiJzdW53dWtvbmdAZ21haWwuY29tIiwiaWF0IjoxNjU5NDU0ODI1LCJleHAiOjE2NTk0ODAwMjV9.T6ty88FqVNHMRgiZTBSjJu0vGxMgJ3lVfUq7TGFzZaY

{
    "id": "62e94f7d07c0bf1340e4541f"
}