###
GET http://localhost:8081/getPlaceUser HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYTM1ZjFkYWMwMDQ4NjlhYjUxMjVhIiwiZW1haWwiOiJUZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY2MzExMDkzMCwiZXhwIjoxNjYzMTM2MTMwfQ.wwQyWz_F7aJzv-R8iXOgmAWlKomypCbT1pDCQa7MInk

