###
POST http://localhost:8081/createRent HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMyMGE5MGViNGRmODQzODk0OWI1OTY0IiwiZW1haWwiOiJsYW1vdWNoZUBnbWFpbC5jb20iLCJpYXQiOjE2NjMwODY1MzEsImV4cCI6MTY2MzExMTczMX0.zYzAFETpaTj_vvMbAvKD17id0ve442PFASfOZBcw3HA

{
    "fk_pls": "6320f8a2d245c86340c4bce8",
    "fk_place": "6320f8a2d245c86340c4bce6",
    "fk_user": "630a35f1dac004869ab5125a"
}

###
POST http://localhost:8081/getRentByIdUSer HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYTM1ZjFkYWMwMDQ4NjlhYjUxMjVhIiwiZW1haWwiOiJUZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY2MzExODgyMywiZXhwIjoxNjYzMTQ0MDIzfQ.SdiQ0jDlUaHfopmXIgo0ihcwk7Z00DWJRfOmDOYXMCk

{
    "id": "630a35f1dac004869ab5125a" 
}