###
POST http://localhost:8081/createSubs HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMyMGE5MGViNGRmODQzODk0OWI1OTY0IiwiZW1haWwiOiJsYW1vdWNoZUBnbWFpbC5jb20iLCJpYXQiOjE2NjMxMjE4NzgsImV4cCI6MTY2MzE0NzA3OH0.6qwEdsD712p-TNfvyXMVvYTY2JWMcPWacT-oQkoICzI

{
    "name": "Prenium",
    "price": 30,
    "services": [
        { "service": "62e7d867cd167f34887fe849"} ,
        { "service": "632139f58edda1401435293c"} 
    ]
}

###
GET http://localhost:8081/getSub HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMyMGE5MGViNGRmODQzODk0OWI1OTY0IiwiZW1haWwiOiJsYW1vdWNoZUBnbWFpbC5jb20iLCJpYXQiOjE2NjMxMjk3OTksImV4cCI6MTY2MzE1NDk5OX0.S0VnsMIWYYMkV3DEjOrdGajcrJdN8YEUHAzJy3wBlBI