###
POST http://localhost:8081/signUp HTTP/1.1
Content-Type: application/json

{
    "firstname": "test",
    "phonenumber": "0603060607",
    "lastname": "test",
    "pseudo": "test",
    "email": "test@gmail.com",
    "password": "test"
}

###
POST http://localhost:8081/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###
POST http://localhost:8081/logout HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYTNkNGNlN2ZhNjM5Yjk5NWE0NTVmIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY2MTYzOTM0NCwiZXhwIjoxNjYxNjY0NTQ0fQ.0peUYCbP8X1Tu1ySJzRU3wxJ5QpNSmUXjAAFfvQcHjE

###
GET http://localhost:8081/getProfile HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYTNkNGNlN2ZhNjM5Yjk5NWE0NTVmIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY2MTY5NjM1OSwiZXhwIjoxNjYxNzIxNTU5fQ.0KMHHHT-db4qk0PFj6BQB6STvLEmd3a1HMbbMb6i1O4

###
PUT http://localhost:8081/updateProfile HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwYTNkNGNlN2ZhNjM5Yjk5NWE0NTVmIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY2MjEzMjU3MCwiZXhwIjoxNjYyMTU3NzcwfQ.vX0PjcVyWZbNHVlgEckbn_lZjBm6UsTlD-J6_3yCmsM

{
    "firstname": "Test",
    "phonenumber": "0634067407",
    "lastname": "Test",
    "pseudo": "Gkt"
}