###
POST http://localhost:8081/signUp HTTP/1.1
Content-Type: application/json

{
    "firstname": "Yanis",
    "phonenumber": "0606060606",
    "lastname": "Wukong",
    "pseudo": "SunWukong",
    "email": "YanisWukong@gmail.com",
    "password": "123456789Wu"
}

###
POST http://localhost:8081/login HTTP/1.1
Content-Type: application/json

{
    "email": "songoku@gmail.com",
    "password": "123456789Sg"
}

###
POST http://localhost:8081/logout HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJlNzk3ODM2MTUwMTUxYzUwYjI0ZGM4IiwiZW1haWwiOiJzb25nb2t1QGdtYWlsLmNvbSIsImlhdCI6MTY1OTM0NTA1NywiZXhwIjoxNjU5MzcwMjU3fQ.PAk9FH0W8jw9HxAvhxoSeDinVEV1M3h1zxvixueajA8