###
POST http://localhost:8081/signUp HTTP/1.1
Content-Type: application/json

{
    "firstname": "Yanis",
    "phonenumber": "0606060606",
    "lastname": "Wukong",
    "pseudo": "SunWukong",
    "email": "YanisWukong@gmail.com",
    "password": "123456789Wu"
}

###
POST http://localhost:8081/login HTTP/1.1
Content-Type: application/json

{
    "email": "gkata@gmail.com",
    "password": "123456"
}

###
POST http://localhost:8081/logout HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJlYmJlZGZhMmRiNGFiOTRmODUzMDg4IiwiZW1haWwiOiJna2F0YUBnbWFpbC5jb20iLCJpYXQiOjE2NTk2MjE0MTksImV4cCI6MTY1OTY0NjYxOX0.QA1XQUwq8T8awnI6TYJz1_-Srwsn-SpNdQturTwKYa4